# Services definition for building & deploying

services:

  app:
    # Extends
    extends:
      file: ./app/docker-compose-app.yml
      service: app
    # Deploy override
    ports: !override
      - ${APP_PORT:-8080}:${APP_DOCKER_PORT:-8080} # HTTP
