# Services overrides for testing in development

services:

  # Inherited
  app:
    # Build override
    image: ${IMAGES_PREFIX:-app}-test-watch-app:${IMAGES_TAG:-latest}
    build:
      target: app_test_watch
    # Deploy override
    develop: !override
      watch:
        # Docker image
        - action: rebuild
          path: ./app/Dockerfile
        # Application build files
        - action: rebuild
          path: ./app/app/uv.lock
        - action: rebuild
          path: ./app/docker/test-watch-command.sh
        # Application source code
        - action: sync
          path: ./app/app
          target: /workdir/app
        - action: sync
          path: ./app/test
          target: /workdir/app/test
