# Services definition for running CLI commands

services:

  # :: app

  app-volumes:
    # Build
    image: matiboux/chown-volumes:latest
    # Deploy
    environment:
      UID: ${DOCKER_UID:-${UID:-1000}}
      VOLUMES: |
        /workdir/app
        /workdir/docker
        /workdir/test
        /opt/venv
    volumes:
      - ./app/app:/workdir/app
      - ./app/docker:/workdir/docker
      - ./app/test:/workdir/test
      - ./app/.venv:/opt/venv

  app:
    # Extend
    extends:
      file: ./docker-compose.yml
      service: app
    # Build override
    image: ${IMAGES_PREFIX:-app}-cli-app:${IMAGES_TAG:-latest}
    build:
      target: app_cli
      args: !override
        UID: ${DOCKER_UID:-${UID:-1000}}
    # Deploy override
    depends_on: !override
      app-volumes:
        condition: service_completed_successfully
    user: ${DOCKER_UID:-${UID:-1000}}
    extra_hosts:
      - host.docker.internal:host-gateway
    tmpfs:
      - /tmp:mode=1777,exec,uid=${DOCKER_UID:-${UID:-1000}},gid=0
    volumes:
      - ./app/app:/workdir/app
      - ./app/docker:/workdir/docker
      - ./app/test:/workdir/test
      - ./app/.venv:/opt/venv
    ports: !reset null
