[project]
name = "python-template"
version = "0.1.0"
description = "Template project for a Python web application."
requires-python = ">=3.14"
authors = [
  {name = "Matiboux", email = "matiboux@gmail.com"},
]
maintainers = [
  {name = "Matiboux", email = "matiboux@gmail.com"},
]
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.14.3",
]
