# Services template for scanning filesystems

services:

  scan-fs:
    # Build
    image: ${IMAGES_PREFIX:-app}-scan-fs:${IMAGES_TAG:-latest}
    build:
      context: .
      dockerfile: ./scan.Dockerfile
      target: app_scan_fs
    # Deploy
    # volumes:
    #   - ./app:/app  # Edit this!
